DEFINITION
FUNCTION
__fede__get_nextpeople_qss
ENDFUNCTION
INCLUDEDIRECTORY
/home/joaquin/work/development/qss-solver/src/usr/include
ENDINCLUDEDIRECTORY
LIBRARYDIRECTORY
/home/joaquin/work/development/qss-solver/lib
ENDLIBRARYDIRECTORY
ENDDEFINITION
DEFINITION
FUNCTION
__fede__get_npeople_qss
ENDFUNCTION
INCLUDEDIRECTORY
/home/joaquin/work/development/qss-solver/src/usr/include
ENDINCLUDEDIRECTORY
LIBRARYDIRECTORY
/home/joaquin/work/development/qss-solver/lib
ENDLIBRARYDIRECTORY
ENDDEFINITION
