name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ qss-solver-dev ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - name: Set the value
      id: step_one
      run: |
        echo "MMOC_PATH=$( pwd )" >> "$GITHUB_ENV"
        echo "MMOC_SRC=$( pwd )/src" >> "$GITHUB_ENV"
        echo "MMOC_DOC=$( pwd )/doc" >> "$GITHUB_ENV"
        echo "MMOC_LIBS=$( pwd )/lib" >> "$GITHUB_ENV"
        echo "MMOC_BUILD=$( pwd )/build" >> "$GITHUB_ENV"
        echo "MMOC_MODELS=$( pwd )/models" >> "$GITHUB_ENV"
        echo "MMOC_OUTPUT=$( pwd )/output" >> "$GITHUB_ENV"
        echo "MMOC_BIN=$( pwd )/bin" >> "$GITHUB_ENV"
        echo "MMOC_PACKAGES=$( pwd )/packages" >> "$GITHUB_ENV"
        echo "MMOC_LIBRARIES=$( pwd )/lib" >> "$GITHUB_ENV"
        echo "MMOC_ENGINE=$( pwd )/src/engine" >> "$GITHUB_ENV"
        echo "MMOC_INCLUDE=$( pwd )/src/usr/include" >> "$GITHUB_ENV"

    - name: Install deps.
      run: | 
        sudo apt-get update
        sudo apt-get install bison++
        sudo apt-get install cmake 
        sudo apt-get install g++
        sudo apt-get install gfortran
        sudo apt-get install gnuplot
        sudo apt-get install libatlas-base-dev
        sudo apt-get install libboost1.83-dev
        sudo apt-get install libcln-dev
        sudo apt-get install libconfig-dev
        sudo apt-get install libginac-dev
        sudo apt-get install libgsl-dev
        sudo apt-get install libmetis-dev
        sudo apt-get install libsbml5-dev
        sudo apt-get install libscotch-dev
        sudo apt-get install libsuitesparse-dev
        sudo apt-get install pkgconf
        sudo apt-get install python3
        sudo apt-get install qtbase5-dev
        sudo apt-get install qtbase5-dev-tools
        sudo apt-get install rapidjson-dev

    - name: Install local deps.
      working-directory: ./src/mmoc/3rd-party/flex
      run: | 
        sudo apt-get install ./flex-old.deb

    - name: Create build folder.
      working-directory: ./src
      run: |
        mkdir -p build

    - name: Configure
      working-directory: ./src/build
      run: |
        cmake ..

    - name: Build
      working-directory: ./src/build
      run: |
        make

    - name: Install
      working-directory: ./src/build
      run: |
        make install

    - name: Tests
      working-directory: ./src/build
      run: make test
