name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ qss-solver-dev ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install deps.
      run: | 
        sudo apt-get update
        sudo apt-get install bison++
        sudo apt-get install boost1.71
        sudo apt-get install cmake 
        sudo apt-get install g++
        sudo apt-get install gfortran
        sudo apt-get install gnuplot
        sudo apt-get install libatlas-base-dev
        sudo apt-get install libcln-dev
        sudo apt-get install libconfig-dev
        sudo apt-get install libginac-dev
        sudo apt-get install libgsl-dev
        sudo apt-get install libsbml5-dev
        sudo apt-get install libscotch-dev
        sudo apt-get install libsuitesparse-dev
        sudo apt-get install pkgconf
        sudo apt-get install python
        sudo apt-get install qt5-default
          
    - name: Build
      working-directory: ./src
      run: make

    - name: Tests
      working-directory: ./src
      run: |
        make test
        for i in mmoc/tests/integration/test_data/*.failed; do cat $i; done
