name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ qss-solver-dev ]

env:
  MMOC_PATH: $GITHUB_WORKSPACE
  MMOC_SRC: $MMOC_PATH/src
  MMOC_DOC: $MMOC_PATH/doc
  MMOC_LIBS: $MMOC_PATH/lib
  MMOC_BUILD: $MMOC_PATH/build
  MMOC_MODELS: $MMOC_PATH/models
  MMOC_OUTPUT: $MMOC_PATH/output
  MMOC_BIN: $MMOC_PATH/bin
  MMOC_PACKAGES: $MMOC_PATH/packages
  MMOC_LIBRARIES: $MMOC_PATH/lib
  MMOC_TESTS: $MMOC_SRC/test-suite
  MMOC_ENGINE: $MMOC_SRC/engine/
  MMOC_INCLUDE: $MMOC_SRC/usr/include

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install deps.
      run: | 
        sudo apt-get update
        sudo apt-get install bison++
        sudo apt-get install boost1.71
        sudo apt-get install cmake 
        sudo apt-get install g++
        sudo apt-get install gfortran
        sudo apt-get install gnuplot
        sudo apt-get install libatlas-base-dev
        sudo apt-get install libcln-dev
        sudo apt-get install libconfig-dev
        sudo apt-get install libginac-dev
        sudo apt-get install libgsl-dev
        sudo apt-get install libsbml5-dev
        sudo apt-get install libscotch-dev
        sudo apt-get install libsuitesparse-dev
        sudo apt-get install pkgconf
        sudo apt-get install python
        sudo apt-get install qt5-default
          
    - name: Build
      working-directory: ./src
      run: make

    - name: Tests
      working-directory: ./src
      run: |
        make test
