name: C/C++ CI

on:
  push:
    branches: [ qss-solver-dev ]
  pull_request:
    branches: [ qss-solver-dev ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Install deps.
      run: | 
        sudo apt-get install libcln-dev
        sudo apt-get install bison++
        sudo apt-get install cmake 
        sudo apt-get install g++
        sudo apt-get install gfortran
        sudo apt-get install gnuplot
        sudo apt-get install libatlas-base-dev
        sudo apt-get install libcln-dev
        sudo apt-get install libconfig-dev
        sudo apt-get install libgsl-dev
        sudo apt-get install libsbml5-dev
        sudo apt-get install libsuitesparse-dev
        sudo apt-get install pkgconf
        sudo apt-get install python
        sudo apt-get install qt5-default
          
    - name: Build
      run: | 
        cd src
        make
